En un notebook escribir la ecuación matemática de cada kernel, crear una clase que permita evaluar  los 10 primeros kernels de la siguiente página [6](http://crsouza.com/2010/03/17/kernel-functions-for-machine-learning-applications/), teniendo en cuenta 1) $x, y \in \mathbb{R}^p$ sean muestras 2) $X,Y \in \mathbb{R}^{N \times P}$ sean conjuntos de muestras. Comprobar el correcto funcionameinto sobre datos sintéticos.

#Linear Kernel (Núcleo Lineal):
$K(X,Y)=X^{T}Y+c$

\\
#Polynomial Kernel (Núcleo Polinomial):
$K(X,Y)=(\alpha X^{T}Y-c)^{d}$

\\
#Gaussian Kernel (Núcleo Gaussiano):
$K(X,Y)=exp(-\frac{||X-Y||^{2}}{2\sigma^{2}})$

\\
#Exponential Kernel (NúcleoExponencial):
$K(X,Y)=exp(-\frac{||X-Y||}{2\sigma^{2}})$

\\
#Laplacian Kernel (Núcleo Laplaciano):
$K(X,Y)=exp(-\frac{||X-Y||}{\sigma})$

\\
#Anova Kernel (Núcleo Anova):
$K(X,Y)=\sum_{k=1}^{n}exp(-\sigma(X^{k}-Y^{k})^{2})^{d}$

\\
#Hyperbolic Tangent (Sigmoid) Kernel (Núcleo de Tangente Hiperbólica(Sigmoide)):
$K(X,Y)=tanh(\alpha X^{T}Y+ c)$

\\
#Rational Quadratic Kernel (Núcleo Cuadrático Rotacional):
$K(X,Y)=1-\frac{||X-Y||^{2}}{||X-Y||^{2}+c}$

\\
#Multiquadric Kernel (Núcleo Multicuadrático):
$K(X,Y)=\sqrt{||X-Y||^{2}+c^{2}}$


\\
#Inverse Multiquadric Kernel (Núcleo Multicuadrático Inverso):
$K(X,Y)=\frac{1}{\sqrt{||X-Y||^{2}+c^{2}}}$

In [132]:
#Libreria útil:
import numpy as np

In [133]:
from numpy.core.arrayprint import format_float_scientific
class Kernel():
  """
  Clase para crear objetos kernel.
  ------------------------------------------------------------------------------------------------------
  ------------------------------------------------------------------------------------------------------
  ATRIBUTOS:
  -X(ndarray):Muestra o conjunto de muestras.
  -Y(ndarray):Muestra o conjunto de muestras.
  ------------------------------------------------------------------------------------------------------
  ------------------------------------------------------------------------------------------------------
  MÉTODOS:
  -Linear_Kernel(método público):Método para evaluar el kernel lineal (parámetro: c)
  -Polynomial_Kernel(método público):Método para evaluar el kernel polynomial(parámetros:alpha,c,d)
  -Gaussian_Kernel(método público):Método para evaluar el kernel gaussiano(parámetros:sigma)
  -Exponential_Kernel(método público):Método para evaluar el kernel exponencial(parámetros:sigma)
  -Laplacian_Kernel(método público): Método para evaluar el kernel laplaciano(parámetros:sigma)
  -Anova_nucleo(método público): Método para evaluar el kernel Anova(parámetros:sigma,n,d)
  -sigmoide(método público): Método para evaluar el kernel sigmoide(parámetros:alpha,c)
  -cuadra_rot_kernel(método público): Método para evaluar el kernel cuadrático racional(parámetros:c)
  -multicuadra_kernel(método público): Método para evaluar el kernel multicuadrático(parámetros:c)
  -multicuadra_inver_kernel(método público): método para evaluar el kernel multicuadrático inverso(parámetros:c)
  """

  def __init__(self, X, Y):
    self.X=X
    self.Y=Y

  def Linear_Kernel(self,c):
    if (self.X.ndim==1 and self.Y.ndim==1):
      X_T=np.transpose(self.X) #Transpuesta (R{P})
      p_punto=np.sum((X_T*self.Y))  #Producto punto (scalar)
      K=p_punto+c #scalar
      OUT=K #Scalar

    elif (self.X.ndim==2 and self.Y.ndim==2):
      N=self.X.shape[0] #N
      P=self.X.shape[1] #P
      OUT=np.zeros((N))
      for i in range(N):
        #Para una sola fila
        X_T=np.transpose(self.X[i,...]) #Transpuesta 
        p_punto=np.sum(X_T*self.Y) #producto punto (scalar)
        K=p_punto+c #scalar
        OUT[i]=K #R{N}
    
    return OUT


  def Polynomial_Kernel(self,alpha,c,d):
    if (self.X.ndim==1 and self.Y.ndim==1):
      X_T=np.transpose(self.X) #Transpuesta (R{P})
      p_punto=alpha*np.sum((X_T*self.Y))  #Producto punto (scalar)
      parentesis=p_punto+c #scalar
      K=parentesis**d #scalar
      OUT=K #Scalar


    elif (self.X.ndim==2 and self.Y.ndim==2):
      N=self.X.shape[0] #N
      P=self.X.shape[1] #P
      OUT=np.zeros((N))
      for i in range(N):
        #Para una sola fila:
        X_T=np.transpose(self.X[i,...]) #Transpuesta 
        p_punto=alpha*np.sum(X_T*self.Y) #producto punto (scalar)
        parentesis=p_punto+c #scalar
        K=parentesis**d #scalar
        OUT[i]=K #R{N}
    
    return OUT


  def Gaussian_Kernel(self,sigma):
    if (self.X.ndim==1 and self.Y.ndim==1):
      resta=self.X-self.Y #R{P}
      norma=np.linalg.norm(resta, ord=2) #Norma 2 (scalar)
      norma_c=norma**2 #scalar
      div=-norma_c/(2*(sigma**2)) #scalar
      K=np.exp(div) #scalar
      OUT=K #scalar

    elif (self.X.ndim==2 and self.Y.ndim==2):
        N=self.X.shape[0] #N
        P=self.X.shape[1] #P
        OUT=np.zeros((N,N))
        for i in range(N):
          #Para una sola fila:
          resta=self.X[i,...]-self.Y #R{NxP}
          norma=np.linalg.norm(resta, ord=2, axis=1) #Norma por filas R{N}
          norma_c=norma**2 #R{N}
          div=-norma_c/(2*sigma**2) #R{N}
          K=np.exp(div) #R{N}
          OUT[i,...]=K #R{NxN}

    return OUT

  def Exponential_Kernel(self,sigma):
    if (self.X.ndim==1 and self.Y.ndim==1):
      resta=self.X-self.Y #R{P}
      norma=np.linalg.norm(resta, ord=2) #Norma 2 (scalar)
      div=-norma/(2*(sigma**2)) #scalar
      K=np.exp(div) #scalar
      OUT=K #scalar

    elif (self.X.ndim==2 and self.Y.ndim==2):
        N=self.X.shape[0] #N
        P=self.X.shape[1] #P
        OUT=np.zeros((N,N))
        for i in range(N):
          #Para una sola fila:
          resta=self.X[i,...]-self.Y #R{NxP}
          norma=np.linalg.norm(resta, ord=2, axis=1) #Norma por filas R{N}
          div=-norma/(2*sigma**2) #R{N}
          K=np.exp(div) #R{N}
          OUT[i,...]=K #R{NxN}

    return OUT

  
  def Laplacian_Kernel(self,sigma):
    if (self.X.ndim==1 and self.Y.ndim==1):
      resta=self.X-self.Y #R{P}
      norma=np.linalg.norm(resta, ord=2) #Norma 2 (scalar)
      div=-norma/sigma #scalar
      K=np.exp(div) #scalar
      OUT=K #scalar

    elif (self.X.ndim==2 and self.Y.ndim==2):
        N=self.X.shape[0] #N
        P=self.X.shape[1] #P
        OUT=np.zeros((N,N))
        for i in range(N):
          #Para una sola fila:
          resta=self.X[i,...]-self.Y #R{NxP}
          norma=np.linalg.norm(resta, ord=2, axis=1) #Norma por filas R{N}
          div=-norma/sigma #R{N}
          K=np.exp(div) #R{N}
          OUT[i,...]=K #R{NxN}

    return OUT

  
  def Anova_Nucleo(self,sigma,n,d):
    if (self.X.ndim==1 and self.Y.ndim==1):
      P=self.X.shape[0]
      OUT=np.zeros((n,P))
      for i in range(n):
        resta=(self.X**i)-(self.Y**i) #R{P}
        resta_c=resta**2 #R{P}
        multipli=-sigma*resta_c #R{P}
        exp=np.exp(multipli) #R{P}
        K=exp**d #R{P}
        OUT[i,...]=K #R{nxP}

    elif (self.X.ndim==2 and self.Y.ndim==2):
      N=self.X.shape[0] #N
      P=self.X.shape[1] #P
      out=np.zeros((n,N,P))
      OUT=np.zeros((N,n,N,P))
      for i in range(N):
        #Para una sola fila
        for j in range(n):
          resta=(self.X[i,...]**i)-(self.Y**i) #R{NxP}
          resta_c=resta**2 #R{NxP}
          multipli=-sigma*resta_c #R{NxP}
          exp=np.exp(multipli) #R{NxP}
          K=exp**d #R{NxP}
          out[j,...]=K #R{nxNxP}
        OUT[i,...]=out #R{NxnxNxP}

    
    return OUT

  def sigmoide(self,alpha,c):
    if (self.X.ndim==1 and self.Y.ndim==1):
      X_T=np.transpose(self.X) #R{P}
      mult=alpha*X_T*self.Y #R{P}
      suma=mult+c #R{P}
      K=np.tanh(suma) #R{P}
      OUT=K #R{P}

    elif (self.X.ndim==2 and self.Y.ndim==2):
        N=self.X.shape[0] #N
        P=self.X.shape[1] #P
        OUT=np.zeros((N,N,P))
        for i in range(N):
          #Para una sola fila:
          X_T=np.transpose(self.X[i,...]) #Transpuesta
          mult=alpha*X_T*self.Y #R{NxP}
          suma=mult+c #R{NxP}
          K=np.tanh(suma) #R{NxP}
          OUT[i,...]=K #R{NxNxP}

    return OUT

  
  def cuadra_rot_kernel(self, c):
    if (self.X.ndim==1 and self.Y.ndim==1):
      resta=self.X-self.Y #R{P}
      norma=np.linalg.norm(resta, ord=2) #scalar
      norma_c=norma**2 #scalar
      frac=norma_c/(norma_c+c) #scalar
      K=1-frac #scalar
      OUT=K #scalar

    elif (self.X.ndim==2 and self.Y.ndim==2):
        N=self.X.shape[0] #N
        P=self.X.shape[1] #P
        OUT=np.zeros((N,N))
        for i in range(N):
          #Para una sola:
          resta=self.X[i,...]-self.Y #R{NxP}
          norma=np.linalg.norm(resta,ord=2,axis=1) #R{N}
          norma_c=norma**2 #R{N}
          frac=norma_c/(norma-c+c) #R{N}
          K=1-frac #R{N}
          OUT[i,...]=K #R{NxN}

    return OUT


  def multicuadra_kernel(self, c):
    if (self.X.ndim==1 and self.Y.ndim==1):
      resta=self.X-self.Y #R{P}
      norma=np.linalg.norm(resta, ord=2) #scalar
      norma_c=norma**2 #scalar
      suma=norma_c+c**2 #scalar
      K=np.sqrt(suma) #scalar
      OUT=K #scalar

    elif (self.X.ndim==2 and self.Y.ndim==2):
        N=self.X.shape[0] #N
        P=self.X.shape[1] #P
        OUT=np.zeros((N,N))
        for i in range(N):
          #Para una sola:
          resta=self.X[i,...]-self.Y #R{NxP}
          norma=np.linalg.norm(resta,ord=2,axis=1) #R{N}
          norma_c=norma**2 #R{N}
          suma=norma_c+c**2 #R{N}
          K=np.sqrt(suma) #R{N}
          OUT[1,...]=K #R{NxN}

    return OUT

  
  def multicuadra_inver_kernel(self, c):
    if (self.X.ndim==1 and self.Y.ndim==1):
      resta=self.X-self.Y #R{P}
      norma=np.linalg.norm(resta, ord=2) #scalar
      norma_c=norma**2 #scalar
      suma=norma_c+c**2 #scalar
      raiz=np.sqrt(suma) #scalar
      K=1/raiz #scalar
      OUT=K #scalar

    elif (self.X.ndim==2 and self.Y.ndim==2):
        N=self.X.shape[0] #N
        P=self.X.shape[1] #P
        OUT=np.zeros((N,N))
        for i in range(N):
          #Para una sola:
          resta=self.X[i,...]-self.Y #R{NxP}
          norma=np.linalg.norm(resta,ord=2,axis=1) #R{N}
          norma_c=norma**2 #R{N}
          suma=norma_c+c**2 #R{N}
          raiz=np.sqrt(suma) #R{N}
          K=1/raiz #R{N}
          OUT[1,...]=K #R{NxN}

    return OUT


#Probando el funcionamiento con un par de muestras:

In [134]:
x=np.arange(0,11,2)
x

array([ 0,  2,  4,  6,  8, 10])

In [135]:
y=np.arange(0,21,4)
y

array([ 0,  4,  8, 12, 16, 20])

In [136]:
kern=Kernel(x,y)
kern.Linear_Kernel(4) #Linear Kernel (En este caso debe devolver un escalar)

444

In [137]:
kern.Polynomial_Kernel(3,2,7) #Polynomial Kernel (En este caso debe devolver un escalar)

-8101865310987104640

In [138]:
kern.Gaussian_Kernel(0.0001) #Gaussian Kernel (En este caso debe devolver un escalar)

0.0

In [139]:
kern.Exponential_Kernel(0.00001) #Exponential Kernel (En este caso debe devolver un escalar)

0.0

In [140]:
kern.Laplacian_Kernel(2)  #Laplacian Kernel (En este caso debe devolver un escalar)

0.0006014311535158234

In [141]:
a=kern.Anova_Nucleo(3,4,3) #Anova Kernel (En este caso debe devolver R{4,6})
print(a,a.shape)

[[1.00000000e+000 1.00000000e+000 1.00000000e+000 1.00000000e+000
  1.00000000e+000 1.00000000e+000]
 [1.00000000e+000 2.31952283e-016 2.89464031e-063 1.94351485e-141
  7.02066780e-251 0.00000000e+000]
 [1.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
  0.00000000e+000 0.00000000e+000]
 [1.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
  0.00000000e+000 0.00000000e+000]] (4, 6)


In [142]:
a=kern.sigmoide(2,6) #Sigmoide (En este caso deb devolver R{6})
print(a,a.shape)

[0.99998771 1.         1.         1.         1.         1.        ] (6,)


In [143]:
kern.cuadra_rot_kernel(2) #Kernel Cuadrático Racional(en este caso debe devolver un escalar)

0.009009009009009028

In [144]:
kern.multicuadra_kernel(2) #Kernel Multicuadratico(en este caso debe devolver un escalar)

14.966629547095765

In [145]:
kern.multicuadra_inver_kernel(2) #Kernel Multicuadratico Inverso(en este caso debe devolver un escalar)

0.0668153104781061

#Probando el funcionamiento entre todos los pares de muestras de los dos conjuntos de muestras:

In [146]:
x=np.random.randint(1,20,(4,5))
x

array([[18, 13,  5,  5,  9],
       [18,  1,  7,  8, 18],
       [14, 10, 10,  1, 12],
       [19,  5, 10, 15,  1]])

In [147]:
y=np.random.randint(1,40,(4,5))
y

array([[11,  4, 22, 31, 29],
       [23, 10, 14, 11, 34],
       [33, 19, 24, 26, 18],
       [ 6, 23,  8, 11, 29]])

In [148]:
kern=Kernel(x,y)
a=kern.Linear_Kernel(4) #Linear Kernel (En este caso debe devolver R{4})
print(a,a.shape)

[3771. 4462. 3665. 3646.] (4,)


In [149]:
a=kern.Polynomial_Kernel(2,3,2) #Polynomial Kernel (En este caso debe devolver R{4})
print(a,a.shape)

[56806369. 79548561. 53655625. 53100369.] (4,)


In [150]:
a=kern.Gaussian_Kernel(2) #Gaussian Kernel (En este caso debe devolver R{4x4})
print(a,a.shape)

[[6.93775077e-82 7.47197234e-43 7.86844816e-63 3.94809638e-38]
 [2.24081523e-51 1.58321429e-23 8.29328334e-64 6.25620584e-42]
 [1.55874650e-75 1.07320386e-37 3.02993632e-71 1.03862026e-34]
 [1.56954587e-68 8.29328334e-64 6.63381541e-55 3.89051524e-71]] (4, 4)


In [151]:
a=kern.Exponential_Kernel(2) #EXponential Kernel (En este caso debe devolver R{4x4})
print(a,a.shape)

[[0.00796137 0.03074287 0.01458322 0.03758684]
 [0.02196882 0.07717053 0.01410797 0.03194485]
 [0.00965598 0.03831181 0.01105132 0.04382727]
 [0.01206255 0.01410797 0.01927604 0.01108973]] (4, 4)


In [152]:
a=kern.Laplacian_Kernel(2) #Laplacian Kernel (En este caso debe devolver R{4x4})
print(a,a.shape)

[[4.01746420e-09 8.93259882e-07 4.52286761e-08 1.99592142e-06]
 [2.32930817e-07 3.54654787e-05 3.96148991e-08 1.04136593e-06]
 [8.69331764e-09 2.15442143e-06 1.49161504e-08 3.68958710e-06]
 [2.11717721e-08 3.96148991e-08 1.38061169e-07 1.51246026e-08]] (4, 4)


In [153]:
a=kern.Anova_Nucleo(2,5,2) #Anova Kernel (En este caso debe devolver R{4x5x4x5})
print(a,a.shape)

[[[[1.00000000e+000 1.00000000e+000 1.00000000e+000 1.00000000e+000
    1.00000000e+000]
   [1.00000000e+000 1.00000000e+000 1.00000000e+000 1.00000000e+000
    1.00000000e+000]
   [1.00000000e+000 1.00000000e+000 1.00000000e+000 1.00000000e+000
    1.00000000e+000]
   [1.00000000e+000 1.00000000e+000 1.00000000e+000 1.00000000e+000
    1.00000000e+000]]

  [[1.00000000e+000 1.00000000e+000 1.00000000e+000 1.00000000e+000
    1.00000000e+000]
   [1.00000000e+000 1.00000000e+000 1.00000000e+000 1.00000000e+000
    1.00000000e+000]
   [1.00000000e+000 1.00000000e+000 1.00000000e+000 1.00000000e+000
    1.00000000e+000]
   [1.00000000e+000 1.00000000e+000 1.00000000e+000 1.00000000e+000
    1.00000000e+000]]

  [[1.00000000e+000 1.00000000e+000 1.00000000e+000 1.00000000e+000
    1.00000000e+000]
   [1.00000000e+000 1.00000000e+000 1.00000000e+000 1.00000000e+000
    1.00000000e+000]
   [1.00000000e+000 1.00000000e+000 1.00000000e+000 1.00000000e+000
    1.00000000e+000]
   [1.00000000e+0

In [154]:
a=kern.sigmoide(2,5) #Sigmoide (En este caso debe retornar R{4x4x5})
print(a,a.shape)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]] (4, 4, 5)


In [155]:
a=kern.cuadra_rot_kernel(2) #Rational cuadratic kernel (En este caso debe retornar R{4x4})
print(a,a.shape)

[[-37.66522986 -26.85677655 -32.82306905 -25.2488095 ]
 [-29.5450487  -19.49390153 -33.0881211  -26.54995463]
 [-36.12142239 -25.0959767  -35.04164258 -24.01999201]
 [-34.34119409 -33.0881211  -30.591138   -35.01388621]] (4, 4)


In [156]:
a=kern.multicuadra_kernel(3) #Multicuadratic kernel (En este caso debe retornar R{4x4})
print(a,a.shape)

[[ 0.          0.          0.          0.        ]
 [35.4682957  34.21987726 31.73326331 36.138622  ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]] (4, 4)


In [157]:
a=kern.multicuadra_inver_kernel(4) #Multicuadratic inverse kernel (En este caso debe retornar R{4x4})
print(a,a.shape)

[[0.         0.         0.         0.        ]
 [0.02811608 0.02913583 0.03140371 0.02759737]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]] (4, 4)
